/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef index_CONSTANTS_H
#define index_CONSTANTS_H

#include "index_types.h"



class indexConstants {
 public:
  indexConstants();

};

extern const indexConstants g_index_constants;



#endif
