// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "thriftSearch.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ;

class thriftSearchHandler : virtual public thriftSearchIf {
 public:
  thriftSearchHandler() {
    // Your initialization goes here
  }

  void search(std::vector<QDocument> & _return, const Query& q) {
    // Your implementation goes here
    printf("search\n");
  }

  void getMonitorKey(std::vector<std::string> & _return) {
    // Your implementation goes here
    printf("getMonitorKey\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<thriftSearchHandler> handler(new thriftSearchHandler());
  shared_ptr<TProcessor> processor(new thriftSearchProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

