/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef indexlog_CONSTANTS_H
#define indexlog_CONSTANTS_H

#include "indexlog_types.h"



class indexlogConstants {
 public:
  indexlogConstants();

};

extern const indexlogConstants g_indexlog_constants;



#endif
