// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Index.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ;

class IndexHandler : virtual public IndexIf {
 public:
  IndexHandler() {
    // Your initialization goes here
  }

  bool addDoc(const std::string& topic, const Document& doc) {
    // Your implementation goes here
    printf("addDoc\n");
  }

  bool updateDoc(const std::string& topic, const Document& doc) {
    // Your implementation goes here
    printf("updateDoc\n");
  }

  bool deleteDoc(const std::string& topic, const int32_t docId) {
    // Your implementation goes here
    printf("deleteDoc\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<IndexHandler> handler(new IndexHandler());
  shared_ptr<TProcessor> processor(new IndexProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

