/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "indexlog_constants.h"



const indexlogConstants g_indexlog_constants;

indexlogConstants::indexlogConstants() {
}



