// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "InnerIndex.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ;

class InnerIndexHandler : virtual public InnerIndexIf {
 public:
  InnerIndexHandler() {
    // Your initialization goes here
  }

  void loadData(std::vector<InnerDocument> & _return, const std::string& topic, const int64_t start, const int32_t num) {
    // Your implementation goes here
    printf("loadData\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<InnerIndexHandler> handler(new InnerIndexHandler());
  shared_ptr<TProcessor> processor(new InnerIndexProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

